Remove singularity from GRAPE
genxnetwork/grape pull request #45
Opened 2022-02-10 10:57 UTC by josephkott

2022-02-10 11:51 UTC, sashaaero approved these changes

2022-02-11 11:20 UTC, alex-medvedev-msc commented on rules/phasing.smk
> +        threads: workflow.cores
phasing works on each {chrom} separately, so there is no need for threads: workflow.cores. Snakemake will automatically launch parallel phasing jobs for {workflow.cores} chromosomes

2022-02-11 11:21 UTC, alex-medvedev-msc requested changes
imputation, phasing and docker container comments

2022-02-11 11:45 UTC, josephkott commented on rules/imputation.smk
> +    threads: workflow.cores
Then I don't understand why we pass parameter `--cpus {threads}` to `minimac4`? Should it be removed as well?

2022-02-11 14:57 UTC, alex-medvedev-msc approved these changes

2022-02-11 15:02 UTC, merged