T cases
genxnetwork/grape pull request #63
Opened 2022-04-25 15:48 UTC by TechWriter81

add test-cases results

2022-05-04 07:58 UTC, alex-medvedev-msc requested changes

2022-05-04 07:58 UTC, alex-medvedev-msc commented on test-cases/aadr.md
> +c0d /media/data/aadr
c0d should be cd?

2022-05-04 07:58 UTC, alex-medvedev-msc commented on test-cases/ibis.md
> +| 3  | 0.9944444444444445  | 0.9944444444444445  |
May be we should round up precision and recall to 3-4 significant digits?

2022-05-13 08:46 UTC, josephkott requested changes
For `aadr.md` and `khazar.md`, I would suggest to remove sections "Test result", "Status", "Notes" from all steps except for the last one, since only the last step contains the actual test result.

`ibis.md` and `king.md` are ok.

2022-05-16 08:40 UTC, alex-medvedev-msc approved these changes

2022-05-17 12:06 UTC, TechWriter81 commented
comments are worked out

2022-05-17 12:07 UTC, merged