fixed empty batches bug
genxnetwork/grape pull request #66
Opened 2022-05-05 14:52 UTC by Jahysama

2022-05-12 17:23 UTC, josephkott requested changes

2022-05-12 17:23 UTC, josephkott commented on scripts/plink_filter.py
> +    p_remove = subprocess.Popen(
Use `subprocess.run` instead.

2022-05-12 18:10 UTC, Jahysama commented on scripts/plink_filter.py
> +                if line.strip("\n") != f"{batch}":
Might work. I did it to extra protect batch variable in case it was an int.

2022-05-13 07:54 UTC, josephkott approved these changes

2022-05-13 07:54 UTC, josephkott commented on scripts/plink_filter.py
> +            raise Error(f"Rule plink_filter for batch{batch} failed with error! See {log} for details.")
```suggestion
            raise Error(f'Rule plink_filter for batch{batch} failed with error! See {log} for details.')
```

2022-05-13 07:59 UTC, merged