Changelog
genxnetwork/grape pull request #70
Opened 2022-05-18 12:26 UTC by TechWriter81

Add a  changelog file to track release notes

2022-05-18 12:29 UTC, josephkott requested changes
Let's use `fixed` everywhere.

2022-05-18 12:29 UTC, josephkott commented on CHANGELOG.md
> +- Fix `germline-king` simulation flow.
```suggestion
- Fixed `germline-king` simulation flow.
```

2022-05-18 12:29 UTC, josephkott commented on CHANGELOG.md
> +- Fix `java command not found` during the `reference` workflow evaluation.
```suggestion
- Fixed `java command not found` during the `reference` workflow evaluation.
```

2022-05-18 12:41 UTC, josephkott approved these changes

2022-05-19 10:28 UTC, sashaaero approved these changes

2022-05-19 11:23 UTC, merged